name: go_cart_rider
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.17
  cached_network_image: null
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  device_info_plus: ^2.0.1
  dio: ^4.0.0
  equatable: ^2.0.0
  fdottedline_nullsafety: ^2.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: 4.0.0-nullsafety.1
  flutter_paystack: ^1.0.5
  flutter_platform_widgets: ^1.1.0
  flutter_polyline_points: ^1.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  flutter_webview_plugin: ^0.4.0
  fluttertoast: ^8.0.8
  flutterwave: ^1.0.0
  geocoding: ^2.0.4
  geolocator: ^8.0.1
  get_it: ^7.2.0
  google_maps_flutter: ^2.1.1
  google_places_flutter: ^2.0.5
  hive: null
  hive_flutter: null
  image_picker: ^0.7.4
  intl: ^0.17.0
  logger: ^1.0.0
  mime: ^1.0.0
  mockito: ^5.0.15
  # monnify_flutter_sdk: ^1.1.0 
  multi_image_picker: ^4.8.0
  open_file: ^3.2.1
  package_info: ^2.0.2
  path_provider: ^2.0.2
  pattern_formatter: ^2.0.0
  percent_indicator: ^3.0.1
  # permission_handler: null
  pin_code_fields: ^7.3.0
  shimmer: ^2.0.0
  stacked: ^2.3.12
  stacked_hooks: ^0.2.2
  stacked_services: ^0.8.26
  url_launcher: null
  uuid: ^3.0.4
  webview_flutter: ^2.0.4

dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter
  hive_generator: null

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
    - assets/image/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MADETOMMY
      fonts:
        - asset: assets/fonts/made_tommy/MADE_TOMMY_Thin.otf
        - asset: assets/fonts/made_tommy/MADE_TOMMY_Light.otf
        - asset: assets/fonts/made_tommy/MADE_TOMMY_Regular.otf
        - asset: assets/fonts/made_tommy/MADE_TOMMY_Medium.otf
        - asset: assets/fonts/made_tommy/MADE_TOMMY_Bold.otf
        - asset: assets/fonts/made_tommy/MADE_TOMMY_ExtraBold.otf
        - asset: assets/fonts/made_tommy/MADE_TOMMY_Black.otf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
